
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

#steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', 'https://github.com/flutter/flutter']
#  dir: '/workspace'

# To run flutter build apk, one must need to  be at the root of the project, the script simply cd to the root before
# running the build command
#- name: 'gcr.io/gespco-cfj5b/repo-gespco'
#  entrypoint: '/bin/bash'
#  args: ['build. sh']

# apk artifacts can be pushed to a GCS bucket like this
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', '/workspace/flutter/examples/hello_world/build/app/outputs/apk/release/app-release.apk', 'gs://$MY_BUCKET/hello_world.apk']

#tags: ['cloud-builders-community']

steps:
  # Step 0: Flutter install
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter']
    dir: '/workspace'

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker-whale', '-f', 'Dockerfile', '.']

  # Step 3: Deploy to Firebase Hosting
  - name: 'bash'
    args: ['./start-apache.bash']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/gespco-cfj5b1/repo-gespco'

timeout: '1200s'