import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:gespco/src/shared/classes/dataEvent.dart';

class Firestore {
  static void newUser(String data) async {
    final dataEncode = jsonEncode(data);
    print("NuevoUsuario?: $dataEncode");
    final addUser = await Firestore.addOrUpdateWithId(
        "user_access", data, dataEncode as Map<String, dynamic>);
    print("Añadido?: $addUser");
  }

  // Obtener entradas
  static Future<List<DataEvent>> getEvents(String col) async {
    return (await FirebaseFirestore.instance
            .collection(col)
            .orderBy(FieldPath.documentId)
            .get())
        .docs
        .map((item) => DataEvent.fromMap(item.data()))
        .toList();
  }

  // Obtener todas entradas de los eventos
  static Future<List<DataEvent>> getAllEntries(String collection) async {
    return (await FirebaseFirestore.instance
            .collection(collection)
            .orderBy(FieldPath.documentId)
            .get())
        .docs
        .map((item) => DataEvent.fromMap(item.data()))
        .toList();
  }

  // Obtener por id
  static Future<List<DataEvent>> getAllEventsSortedById(
      String collection) async {
    return (await FirebaseFirestore.instance
            .collection(collection)
            .orderBy("id", descending: false)
            .get())
        .docs
        .map((item) => DataEvent.fromMap(item.data()))
        .toList();
  }

  // Actualiar entry
  static Future updateEntryWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .update(data);
  }

  // Añadir por id
  static Future addOrUpdateWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .set(data);
  }

  // Borrar entradas
  static Future deleteEntry(String collection, String documentId) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .delete();
  }

/*
  // get with filter
  static Future<List<DataEvent>> getAllEventsFilteredByPrice(
      String collection) async {
    return (await FirebaseFirestore.instance
            .collection(collection)
            .where("price", isGreaterThan: 60000)
            .get())
        .docs
        .map((item) => Car.fromMap(item.data()))
        .toList();
  }

  static Future addEntryWithAutogeneratedId(
      String collection, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance.collection(collection).add(data);
  }
*/
}
