// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_DOsGUrB9m5drjyT9HvQNWoc5BFSgEME',
    appId: '1:994700819032:web:82dfecddf7eef2c060282d',
    messagingSenderId: '994700819032',
    projectId: 'gespco-cfj5b1',
    authDomain: 'gespco-cfj5b1.firebaseapp.com',
    storageBucket: 'gespco-cfj5b1.appspot.com',
    measurementId: 'G-VY4833538T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALmDYd0i08X7TtFKN8VllB1qzsJZ3IAxM',
    appId: '1:994700819032:android:099e81b19efd411860282d',
    messagingSenderId: '994700819032',
    projectId: 'gespco-cfj5b1',
    storageBucket: 'gespco-cfj5b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh0yeqaV7NGx_hiNTL5cLjlOiRpysYsQE',
    appId: '1:994700819032:ios:dbdf60d3ec0223dc60282d',
    messagingSenderId: '994700819032',
    projectId: 'gespco-cfj5b1',
    storageBucket: 'gespco-cfj5b1.appspot.com',
    iosClientId:
        '994700819032-uqobun3d6oh5dcs0pka9ogufg3b6li01.apps.googleusercontent.com',
    iosBundleId: 'com.example.gespco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh0yeqaV7NGx_hiNTL5cLjlOiRpysYsQE',
    appId: '1:994700819032:ios:d93425b544f3d6b760282d',
    messagingSenderId: '994700819032',
    projectId: 'gespco-cfj5b1',
    storageBucket: 'gespco-cfj5b1.appspot.com',
    iosClientId:
        '994700819032-deone7p116lefpomnllmq0lv278gu5sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gespco.RunnerTests',
  );
}
